os:
  - linux
  - osx
language: objective-c
rvm: 2.2
osx_image: xcode8.2
env:
  global:
    - IOS_SIMULATOR="iPhone 6s"
matrix:
  include:
    - os: osx
      env: BUILD_SCHEME="SQLite iOS"
    - os: osx
      env: BUILD_SCHEME="SQLite Mac"
    - os: osx
      env: VALIDATOR_SUBSPEC="none"
    - os: osx
      env: VALIDATOR_SUBSPEC="standard"
    - os: osx
      env: VALIDATOR_SUBSPEC="standalone"
    - os: osx
      env: VALIDATOR_SUBSPEC="SQLCipher"
    - os: osx
      env: CARTHAGE_PLATFORM="iOS"
    - os: osx
      env: CARTHAGE_PLATFORM="Mac"
    - os: osx
      env: CARTHAGE_PLATFORM="watchOS"
    - os: osx
      env: CARTHAGE_PLATFORM="tvOS"
    - os: osx
      env: PACKAGE_MANAGER_COMMAND="test -Xlinker -lsqlite3"
    - os: linux
      env: PACKAGE_MANAGER_COMMAND="test -Xlinker -lsqlite3"
before_install:
  - gem update bundler
  - gem install xcpretty --no-document
  - brew update
  - brew outdated carthage || brew upgrade carthage
script:
  - ./run-tests.sh
